name: nebu_guid_master
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  provider: ^6.0.3
  intl: ^0.17.0
  path_provider: ^2.0.14
  path: ^1.8.0
  printing: ^5.9.2
  image: ^3.0.2
  device_info: ^2.0.2
  ntp: ^2.0.0
  cached_network_image: ^3.2.1
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  pdf: ^3.8.0
  pdf_render: ^1.4.0
  persian_number_utility: ^0.3.4
  file: ^6.1.4
  quiver: ^3.0.1
  pretty_qr_code_plus: ^0.0.1
  qr: ^3.0.1
  excel: ^3.0.0
  lottie: ^1.2.1
  google_fonts: ^4.0.4
  camera: ^0.10.0
  cloud_firestore: ^4.14.0
  searchfield: ^1.0.9
  open_file: ^3.1.1
  line_icons: ^2.0.1
  supercharged: ^2.0.0
  flutter_linkify: 5.0.2
  smooth_page_indicator: ^1.0.0+2
  url_launcher: ^6.1.10
  carousel_slider: ^5.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true


  assets:
    - assets/
    - assets/images/
    - assets/fonts/Cairo.ttf




  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo.ttf






