// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvzalqkN9VeJFsY_yhKFsegbOyAxJN6DY',
    appId: '1:747187675082:web:e44cea524076dea1947933',
    messagingSenderId: '747187675082',
    projectId: 'nebu-guid-master',
    authDomain: 'nebu-guid-master.firebaseapp.com',
    storageBucket: 'nebu-guid-master.appspot.com',
    measurementId: 'G-Q3PRM6W8QG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYDC7ddMrZIYsUgyj9TmChGg7do1T5Xmo',
    appId: '1:747187675082:android:45979eb1e3f4b7ea947933',
    messagingSenderId: '747187675082',
    projectId: 'nebu-guid-master',
    storageBucket: 'nebu-guid-master.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMhW0Urk5mkxTkf-RsvXwLr-Ps2su3lGM',
    appId: '1:747187675082:ios:5af2ca74b5f46a45947933',
    messagingSenderId: '747187675082',
    projectId: 'nebu-guid-master',
    storageBucket: 'nebu-guid-master.appspot.com',
    iosBundleId: 'com.example.nebuGuidMaster',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMhW0Urk5mkxTkf-RsvXwLr-Ps2su3lGM',
    appId: '1:747187675082:ios:5af2ca74b5f46a45947933',
    messagingSenderId: '747187675082',
    projectId: 'nebu-guid-master',
    storageBucket: 'nebu-guid-master.appspot.com',
    iosBundleId: 'com.example.nebuGuidMaster',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvzalqkN9VeJFsY_yhKFsegbOyAxJN6DY',
    appId: '1:747187675082:web:9010889b9d848de3947933',
    messagingSenderId: '747187675082',
    projectId: 'nebu-guid-master',
    authDomain: 'nebu-guid-master.firebaseapp.com',
    storageBucket: 'nebu-guid-master.appspot.com',
    measurementId: 'G-1Z9N29BE5K',
  );

}