// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsTyPGvFr2dKHmLvV_kXsKK1CzJI1GHgs',
    appId: '1:1082544707586:web:8f6c7e806838d665f8ef1b',
    messagingSenderId: '1082544707586',
    projectId: 'nebu-guide',
    authDomain: 'nebu-guide.firebaseapp.com',
    storageBucket: 'nebu-guide.appspot.com',
    measurementId: 'G-QSJE8VF0DF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzT47xryzEs4078xFw3W9fN6OveuQmG1I',
    appId: '1:1082544707586:android:641f3f5e4dc157b7f8ef1b',
    messagingSenderId: '1082544707586',
    projectId: 'nebu-guide',
    storageBucket: 'nebu-guide.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDboxP7TIR2zRzUF4oG-2fMS6SHmZ1OAP8',
    appId: '1:1082544707586:ios:c6268a3ed522ceaaf8ef1b',
    messagingSenderId: '1082544707586',
    projectId: 'nebu-guide',
    storageBucket: 'nebu-guide.appspot.com',
    iosBundleId: 'com.nebusystems.nebu_guide',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDboxP7TIR2zRzUF4oG-2fMS6SHmZ1OAP8',
    appId: '1:1082544707586:ios:c6268a3ed522ceaaf8ef1b',
    messagingSenderId: '1082544707586',
    projectId: 'nebu-guide',
    storageBucket: 'nebu-guide.appspot.com',
    iosBundleId: 'com.nebusystems.nebu_guide',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsTyPGvFr2dKHmLvV_kXsKK1CzJI1GHgs',
    appId: '1:1082544707586:web:c76d98ee1b1a026cf8ef1b',
    messagingSenderId: '1082544707586',
    projectId: 'nebu-guide',
    authDomain: 'nebu-guide.firebaseapp.com',
    storageBucket: 'nebu-guide.appspot.com',
    measurementId: 'G-X64RT2HQJT',
  );
}
